### ISSUE TITLE
ValueError: could not convertstring to float: 'N/A'

### ISSUE THREAD

**Issue by jmramosr** [nec4/gpu-array#1]
Hello and great work with the tool!
I'm really inspired how you made that TUI!

I have an issue installing the gpu-array.
Version of my OS: Ubuntu 20.04.6 LTS
CPU: Intel Core I9-11900KF
Nvidia-smi installed: NVIDIA-SMI 525.85.12 | Driver Version 525.85.12 | Cuda Version: 12.0

Steps I've made:
- Use a virtual environment with virtualenv
- Go to the virtual environment
- Install urwid with pip
- Go to the folder
- `pip install .`
- execute `gpu-array`

And the message is:
```
Traceback (most recent call last):
  File "/home/xxx/venv/bin/gpu-array", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/venv/lib/python3.8/site-packages/gpu_array/scripts/__main__.py", line 21, in main
    tracker = Tracker(query)
  File "/home/xxx/venv/lib/python3.8/site-packages/gpu_array/query.py", line 147, in __init__
    self.poll()
  File "/home/xxx/venv/lib/python3.8/site-packages/gpu_array/query.py", line 167, in poll
    all_gpu_props = {i: GPUQuery.parse_gpu_props(gpu) for i, gpu in enumerate(gpus)}
  File "/home/xxx/venv/lib/python3.8/site-packages/gpu_array/query.py", line 167, in <dictcomp>
    all_gpu_props = {i: GPUQuery.parse_gpu_props(gpu) for i, gpu in enumerate(gpus)}
  File "/home/xxx/venv/lib/python3.8/site-packages/gpu_array/query.py", line 70, in parse_gpu_props
    gpu_props["max_temp"] = float(
ValueError: could not convert string to float: 'N/A'
```

It seems Nvidia-smi has changed the outputted xml format. Can you check it?

Thanks in advance.

**Comment by nec4** [comment]
Hey! Thanks for the detailed report. At the moment I only have access to GPUs on shared clusters, so I'm not sure if I can do much to test other versions of `nvidia-smi` (no admin priveleges), but I will look around!

**Comment by jmramosr** [comment]
> Hey! Thanks for the detailed report. At the moment I only have access to GPUs on shared clusters, so I'm not sure if I can do much to test other versions of `nvidia-smi` (no admin priveleges), but I will look around!

If you need, I could pass you my Nvidia-smi xml file, if it helps.

The log is here: https://gist.github.com/jmramosr/14bea45baaea90ebfb8b358bf97d2c82

Thanks in advance!

**Comment by nec4** [comment]
That helps - thanks!
